/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedImportExportRouteImport } from './routes/_authenticated/import-export'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedVerificationRouteImport } from './routes/_authenticated/verification'
import { Route as AuthenticatedAssetsIndexRouteImport } from './routes/_authenticated/assets.index'
import { Route as AuthenticatedAssetsIdRouteImport } from './routes/_authenticated/assets.$id'
import { Route as AuthenticatedLocationsIndexRouteImport } from './routes/_authenticated/locations.index'
import { Route as AuthenticatedLocationsCenterIdRouteImport } from './routes/_authenticated/locations.$centerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportExportRoute =
  AuthenticatedImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerificationRoute =
  AuthenticatedVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsIndexRoute =
  AuthenticatedAssetsIndexRouteImport.update({
    id: '/assets/',
    path: '/assets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsIdRoute = AuthenticatedAssetsIdRouteImport.update({
  id: '/assets/$id',
  path: '/assets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocationsIndexRoute =
  AuthenticatedLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLocationsCenterIdRoute =
  AuthenticatedLocationsCenterIdRouteImport.update({
    id: '/locations/$centerId',
    path: '/locations/$centerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/import-export': typeof AuthenticatedImportExportRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/locations/$centerId': typeof AuthenticatedLocationsCenterIdRoute
  '/assets/': typeof AuthenticatedAssetsIndexRoute
  '/locations/': typeof AuthenticatedLocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/import-export': typeof AuthenticatedImportExportRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/verification': typeof AuthenticatedVerificationRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/locations/$centerId': typeof AuthenticatedLocationsCenterIdRoute
  '/assets': typeof AuthenticatedAssetsIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/import-export': typeof AuthenticatedImportExportRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/verification': typeof AuthenticatedVerificationRoute
  '/_authenticated/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/_authenticated/locations/$centerId': typeof AuthenticatedLocationsCenterIdRoute
  '/_authenticated/assets/': typeof AuthenticatedAssetsIndexRoute
  '/_authenticated/locations/': typeof AuthenticatedLocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/assignments'
    | '/dashboard'
    | '/employees'
    | '/import-export'
    | '/maintenance'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/verification'
    | '/assets/$id'
    | '/locations/$centerId'
    | '/assets/'
    | '/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/assignments'
    | '/dashboard'
    | '/employees'
    | '/import-export'
    | '/maintenance'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/verification'
    | '/assets/$id'
    | '/locations/$centerId'
    | '/assets'
    | '/locations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/assignments'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/import-export'
    | '/_authenticated/maintenance'
    | '/_authenticated/reports'
    | '/_authenticated/scan'
    | '/_authenticated/settings'
    | '/_authenticated/verification'
    | '/_authenticated/assets/$id'
    | '/_authenticated/locations/$centerId'
    | '/_authenticated/assets/'
    | '/_authenticated/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-export': {
      id: '/_authenticated/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof AuthenticatedImportExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verification': {
      id: '/_authenticated/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AuthenticatedVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/': {
      id: '/_authenticated/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AuthenticatedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets/$id': {
      id: '/_authenticated/assets/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAssetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations/': {
      id: '/_authenticated/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthenticatedLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations/$centerId': {
      id: '/_authenticated/locations/$centerId'
      path: '/locations/$centerId'
      fullPath: '/locations/$centerId'
      preLoaderRoute: typeof AuthenticatedLocationsCenterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedImportExportRoute: typeof AuthenticatedImportExportRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVerificationRoute: typeof AuthenticatedVerificationRoute
  AuthenticatedAssetsIdRoute: typeof AuthenticatedAssetsIdRoute
  AuthenticatedLocationsCenterIdRoute: typeof AuthenticatedLocationsCenterIdRoute
  AuthenticatedAssetsIndexRoute: typeof AuthenticatedAssetsIndexRoute
  AuthenticatedLocationsIndexRoute: typeof AuthenticatedLocationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedImportExportRoute: AuthenticatedImportExportRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVerificationRoute: AuthenticatedVerificationRoute,
  AuthenticatedAssetsIdRoute: AuthenticatedAssetsIdRoute,
  AuthenticatedLocationsCenterIdRoute: AuthenticatedLocationsCenterIdRoute,
  AuthenticatedAssetsIndexRoute: AuthenticatedAssetsIndexRoute,
  AuthenticatedLocationsIndexRoute: AuthenticatedLocationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
